### ISSUE TITLE
Add heads or tails function

### ISSUE THREAD

**Issue by mechdragon23** [mechdragon23/gamba#1]
- implement a new headsOrTails.cpp file
- add the necessary headers in myHeader.h
- delete the comment in main and place in your headsOrTails function

function requirements:
- prompt the user for heads or tails
- generate heads or tails randomly
- output heads or tails and if the user won or not

nice to have:
- use system ("CLS") to clear the screen after user input
- show ascii art of heads or tails for the output

**Comment by qgarcia95** [comment]
Hey Alex, can you assign this to me?
