### ISSUE TITLE
implement dice function

### ISSUE THREAD

**Issue by mechdragon23** [mechdragon23/gamba#3]
- implement a new dice.cpp file
- add the necessary headers in myHeader.h
- delete the comment in main and place in your dice function

function requirements:
- prompt the user for a numerical input for what number the dice will add up to
- roll 2 dice and add the values
- output the value and if the user won or not

nice to have:
- use system ("CLS") to clear the screen after user input
- show ascii art of the dice for the output

**Comment by Midknightsnack** [comment]
Is it okay if I take this issue ? 👀
I'm a bit rusty with C++ but I think I got it.
