### ISSUE TITLE
implement slots function

### ISSUE THREAD

**Issue by mechdragon23** [mechdragon23/gamba#5]
- implement a new slots.cpp file
- add the necessary headers in myHeader.h
- delete the comment in main and place in your slots function

function requirements:
- output 3 randomly selected symbols in a row(ex. "$" "$" "$") from a set of 4 (ex. "@" "%" "#" "$")
- if the 3 output symbols match, display that the user has won if not, then lose
- option to spin again or quit 

nice to have:
- use system ("CLS") to clear the screen after each spin

**Comment by elara04** [comment]
i would like to be assigned to this issue to try to contribute to your repo

**Comment by elara04** [comment]
also am I  just implementing the function with the additional requirements winthin main.cpp or am I supposed to create a separate slots.cpp file and use your header to prototype the slots function and include your header in my slots.cpp file where I define the function in slots.cpp  and just call the function in your main.cpp?

**Comment by mechdragon23** [comment]
yea, create a separate slots.cpp file, include the prototype in the header file, and call the function in main
